/* eslint-disable react/react-in-jsx-scope */
import Head from 'next/head';
import styles from '../styles/Home.module.css';

import Navbar from '../components/Navbar';
import Footer from '../components/Footer';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Futrome</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo_green.svg" />
      </Head>

      <Navbar />
      <main className={styles.main} />

      <Footer />
    </div>
  );
}
