/* eslint-disable react/react-in-jsx-scope */
import Head from 'next/head';

import Home from './home';

export default function LandingPage() {
  return (
    <div>
      <Head>
        <title>Futrome</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo_green.svg" />
      </Head>

      <Home />

    </div>
  );
}
